
DATA:
  data_root: /scratch/hl3797/dataset/VOCdevkit/VOC2012
  train_list: ./lists/pascal/voc_sbd_merge_noduplicate.txt  # all training data (merged from both dataset)
  val_list: ./lists/pascal/val.txt                          # all val data  (only val in pascal is enough)
  classes: 2


TRAIN:
  layers: 50
  sync_bn: False
  train_h: 473
  train_w: 473
  val_size: 473
  scale_min: 0.9    # minimum random scale
  scale_max: 1.1    # maximum random scale
  rotate_min: -10   # minimum random rotate
  rotate_max: 10    # maximum random rotate
  zoom_factor: 8    # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  padding_label: 255
  aux_weight: 1.0
  train_gpu: [0]    # not in use for now
  cuda: True
  workers: 4        # data loader workers
  batch_size: 4     # batch size for training
  batch_size_val: 1
  base_lr: 0.0025
  epochs: 200
  start_epoch: 0
  power: 0.9        # 0 means no decay
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed: 321
  print_freq: 100
  save_freq: 20
  save_path: exp/pascal/split0_resnet50/model
  weight:           # load weight for fine-tuning or testing
  resume:           # path to latest checkpoint (default: none)
  evaluate: True
  split: 0
  shot: 1
  vgg: False
  ppm_scales: [60, 30, 15, 8]
  fix_random_seed_val: True
  warmup: False
  use_coco: False
  use_split_coco: False
  resized_val: True # resize val is only used in valuation, NOT in test
  ori_resize: True  # use original label for evaluation

# deprecated multi-processing training
Distributed:
  multiprocessing_distributed: False
#  dist_url: tcp://127.0.0.1:6789
#  dist_backend: 'nccl'
#  world_size: 1
#  rank: 0
#  use_apex: False
#  opt_level: 'O0'
#  keep_batchnorm_fp32:
#  loss_scale:

